function f = LightSourceResidual(in1,L,in3,in4,in5,in6,rho)
%LIGHTSOURCERESIDUAL
%    F = LIGHTSOURCERESIDUAL(IN1,L,IN3,IN4,IN5,IN6,RHO)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    04-Feb-2021 12:08:44

phi_0 = in1(1);
mu = in1(2);
r_d = in1(3);

n1 = in4(1,:)';
n2 = in4(2,:)';
n3 = in4(3,:)';

s1 = in5(1);
s2 = in5(2);
s3 = in5(3);

v1 = in6(1);
v2 = in6(2);
v3 = in6(3);


x1 = in3(1,:)';
x2 = in3(2,:)';
x3 = in3(3,:)';

t2 = r_d.^2;
t3 = s1.^2;
t4 = s2.^2;
t5 = s3.^2;
t6 = x1.^2;
t7 = x2.^2;
t8 = x3.^2;
t9 = -x1;
t10 = -x2;
t11 = -x3;
t12 = s1+t9;
t13 = s2+t10;
t14 = s3+t11;
t15 = t12.^2;
t16 = t13.^2;
t17 = t14.^2;
t18 = t15+t16+t17;

f = sum((L-(phi_0.*rho.*t2.*(-s1.*v1-s2.*v2-s3.*v3+v1.*x1+v2.*x2+v3.*x3).^mu.*(n1.*s1+n2.*s2+n3.*s3+n1.*t9+n2.*t10+n3.*t11).*(t3+t4+t5+t6+t7+t8-s1.*x1.*2.0-s2.*x2.*2.0-s3.*x3.*2.0).^(mu.*(-1.0./2.0)))./(pi.*(r_d.*t3.*2.0+r_d.*t4.*2.0+r_d.*t5.*2.0+r_d.*t6.*2.0+r_d.*t7.*2.0+r_d.*t8.*2.0+t2.*sqrt(t18)+t18.^(3.0./2.0)-r_d.*s1.*x1.*4.0-r_d.*s2.*x2.*4.0-r_d.*s3.*x3.*4.0))).^2, 'all');

end