function [f,j] = LightSrcObjLS(in1,L,in3,in4,in5,in6,rho)
%LIGHTSOURCELEASTSQROBJ
%    [F,J] = LIGHTSOURCELEASTSQROBJ(IN1,L,IN3,IN4,IN5,IN6,RHO)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    25-Mar-2021 10:10:57

phi_0 = in1(1);
mu = in1(2);
r_d = in1(3);

n1 = in4(1,:)';
n2 = in4(2,:)';
n3 = in4(3,:)';

s1 = in5(1);
s2 = in5(2);
s3 = in5(3);

v1 = in6(1);
v2 = in6(2);
v3 = in6(3);

x1 = in3(1,:)';
x2 = in3(2,:)';
x3 = in3(3,:)';

t2 = n1.*s1;
t3 = n2.*s2;
t4 = n3.*s3;
t5 = n1.*x1;
t6 = n2.*x2;
t7 = n3.*x3;
t8 = s1.*v1;
t9 = s2.*v2;
t10 = s3.*v3;
t11 = v1.*x1;
t12 = v2.*x2;
t13 = v3.*x3;
t14 = r_d.^2;
t15 = s1.^2;
t16 = s2.^2;
t17 = s3.^2;
t18 = x1.^2;
t19 = x2.^2;
t20 = x3.^2;
t21 = s1.*x1.*2.0;
t22 = s2.*x2.*2.0;
t23 = s3.*x3.*2.0;
t24 = 1.0./pi;
t25 = -x1;
t26 = -x2;
t27 = -x3;
t37 = r_d.*s1.*x1.*4.0;
t38 = r_d.*s2.*x2.*4.0;
t39 = r_d.*s3.*x3.*4.0;
t40 = mu./2.0;
t28 = -t5;
t29 = -t6;
t30 = -t7;
t31 = -t8;
t32 = -t9;
t33 = -t10;
t34 = -t21;
t35 = -t22;
t36 = -t23;
t41 = r_d.*t15.*2.0;
t42 = r_d.*t16.*2.0;
t43 = r_d.*t17.*2.0;
t44 = r_d.*t18.*2.0;
t45 = r_d.*t19.*2.0;
t46 = r_d.*t20.*2.0;
t47 = s1+t25;
t48 = s2+t26;
t49 = s3+t27;
t50 = -t37;
t51 = -t38;
t52 = -t39;
t53 = -t40;
t54 = t47.^2;
t55 = t48.^2;
t56 = t49.^2;
t57 = t11+t12+t13+t31+t32+t33;
t59 = t2+t3+t4+t28+t29+t30;
t64 = t15+t16+t17+t18+t19+t20+t34+t35+t36;
t58 = t54+t55+t56;
t60 = t57.^mu;
t65 = t64.^t53;
t61 = sqrt(t58);
t62 = t61.^3;
t63 = t14.*t61;
t66 = t41+t42+t43+t44+t45+t46+t50+t51+t52+t62+t63;
t67 = 1.0./t66;
f = L-phi_0.*rho.*t14.*t24.*t59.*t60.*t65.*t67;

j = [-rho.*t14.*t24.*t59.*t60.*t65.*t67,-phi_0.*rho.*t14.*t24.*t59.*t60.*t65.*t67.*(log(t57)-log(t64)./2.0),phi_0.*r_d.*rho.*t24.*t59.*t60.*t65.*t67.*-2.0+phi_0.*rho.*t14.*t24.*t59.*t60.*t65.*t67.^2.*(t15.*2.0+t16.*2.0+t17.*2.0+t18.*2.0+t19.*2.0+t20.*2.0+r_d.*t61.*2.0-s1.*x1.*4.0-s2.*x2.*4.0-s3.*x3.*4.0)];

end
