function coefs = ShadingFactorCoeffsUV(s_u,s_v,m_u,m_v,d_u,d_v,zeta_uv,zeta_u,zeta_v)
%SHADINGFACTORCOEFFSUV
%    COEFS = SHADINGFACTORCOEFFSUV(S_U,S_V,M_U,M_V,D_U,D_V,ZETA_UV,ZETA_U,ZETA_V)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    23-Aug-2021 11:51:27

t2 = d_u.*2.0;
t3 = d_v.*2.0;
t4 = s_u.*zeta_uv.*2.0;
t5 = s_v.*zeta_uv.*2.0;
t10 = m_u.*zeta_u.*zeta_v.*zeta_uv.*2.0;
t11 = m_v.*zeta_u.*zeta_v.*zeta_uv.*2.0;
t6 = t4.*zeta_u;
t7 = t4.*zeta_v;
t8 = t5.*zeta_u;
t9 = t5.*zeta_v;
t12 = t6.*zeta_v;
t13 = t8.*zeta_v;
coefs = [2.0,2.0,-2.0,t2-t3-t4+t5+t6+t7-t10+t11+t13-s_v.*zeta_u.*zeta_uv.*2.0-s_v.*zeta_v.*zeta_uv.*2.0-s_u.*zeta_u.*zeta_v.*zeta_uv.*2.0,-t2+t3+t4-t5+t8+t9+t10-t11+t12-s_u.*zeta_u.*zeta_uv.*2.0-s_u.*zeta_v.*zeta_uv.*2.0-s_v.*zeta_u.*zeta_v.*zeta_uv.*2.0];
